"use client";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClientLayout>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableColorScheme
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
